//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.14 at 03:40:33 PM EET 
//


package com.mobiblocks.skippables.vast;

import android.support.annotation.Nullable;

import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 				The AdVerification element is used to initiate a controlled container where code can be
 * 				executed for collecting data to verify ad playback details.
 * 			
 * 
 * <p>Java class for AdVerifications_Wrapper_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdVerifications_Wrapper_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Verification" type="{http://www.iab.com/VAST}Verification_Wrapper_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class AdVerificationsWrapperType {

    @Nullable
    protected List<VerificationWrapperType> verification;

    /**
     * Gets the value of the verification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerificationWrapperType }
     * 
     * 
     */
    @Nullable
    public List<VerificationWrapperType> getVerification() {
        return this.verification;
    }
    
    public void addVerification(VerificationWrapperType verification) {
        if (this.verification == null) {
            this.verification = new ArrayList<>();
        }
        this.verification.add(verification);
    }

}
