//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.14 at 03:40:33 PM EET 
//


package com.mobiblocks.skippables.vast;

import android.support.annotation.NonNull;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Inline_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Inline_type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iab.com/VAST}AdDefinitionBase_type">
 *       &lt;sequence>
 *         &lt;element name="AdTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdVerifications" type="{http://www.iab.com/VAST}AdVerifications_Inline_type" minOccurs="0"/>
 *         &lt;element name="Advertiser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Category" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="authority" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Creatives">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Creative" type="{http://www.iab.com/VAST}Creative_InlineChild_type" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Survey" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class InlineType
    extends AdDefinitionBaseType
{

    @NonNull
    protected String adTitle;
    protected AdVerificationsInlineType adVerifications;
    protected String advertiser;
    protected List<InlineType.Category> category = new ArrayList<>();
    protected InlineType.Creatives creatives;
    protected String description;
    protected InlineType.Survey survey;

    /**
     * Gets the value of the adTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdTitle() {
        return adTitle;
    }

    /**
     * Sets the value of the adTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdTitle(String value) {
        this.adTitle = value;
    }

    /**
     * Gets the value of the adVerifications property.
     * 
     * @return
     *     possible object is
     *     {@link AdVerificationsInlineType }
     *     
     */
    public AdVerificationsInlineType getAdVerifications() {
        return adVerifications;
    }

    /**
     * Sets the value of the adVerifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdVerificationsInlineType }
     *     
     */
    public void setAdVerifications(AdVerificationsInlineType value) {
        this.adVerifications = value;
    }

    /**
     * Gets the value of the advertiser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvertiser() {
        return advertiser;
    }

    /**
     * Sets the value of the advertiser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvertiser(String value) {
        this.advertiser = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InlineType.Category }
     * 
     * 
     */
    @NonNull
    public List<InlineType.Category> getCategory() {
        return this.category;
    }
    
    public void addCategory(@NonNull InlineType.Category category) {
        this.category.add(category);
    }

    /**
     * Gets the value of the creatives property.
     * 
     * @return
     *     possible object is
     *     {@link InlineType.Creatives }
     *     
     */
    public InlineType.Creatives getCreatives() {
        return creatives;
    }

    /**
     * Sets the value of the creatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link InlineType.Creatives }
     *     
     */
    public void setCreatives(InlineType.Creatives value) {
        this.creatives = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the survey property.
     * 
     * @return
     *     possible object is
     *     {@link InlineType.Survey }
     *     
     */
    public InlineType.Survey getSurvey() {
        return survey;
    }

    /**
     * Sets the value of the survey property.
     * 
     * @param value
     *     allowed object is
     *     {@link InlineType.Survey }
     *     
     */
    public void setSurvey(InlineType.Survey value) {
        this.survey = value;
    }

    public LinearInlineChildType getFirstLinearCreative() {
        if (creatives == null) {
            return null;
        }

        List<CreativeInlineChildType> creative = creatives.getCreative();
        if (creative.size() == 0) {
            return null;
        }

        for (CreativeInlineChildType inline:
             creative) {
            LinearInlineChildType linear = inline.getLinear();
            if (linear != null) {
                return linear;
            }
        }

        return null;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="authority" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Category {

        protected String value;
        @NonNull
        protected URL authority;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the authority property.
         * 
         * @return
         *     possible object is
         *     {@link URL }
         *     
         */
        public URL getAuthority() {
            return authority;
        }

        /**
         * Sets the value of the authority property.
         * 
         * @param value
         *     allowed object is
         *     {@link URL }
         *     
         */
        public void setAuthority(URL value) {
            this.authority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Creative" type="{http://www.iab.com/VAST}Creative_InlineChild_type" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Creatives {

        @NonNull
        protected List<CreativeInlineChildType> creative = new ArrayList<>();

        /**
         * Gets the value of the creative property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the creative property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCreative().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CreativeInlineChildType }
         * 
         * 
         */
        @NonNull
        public List<CreativeInlineChildType> getCreative() {
            return this.creative;
        }
        
        public void addCreative(@NonNull CreativeInlineChildType creative) {
            this.creative.add(creative);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Survey {

        protected URL value;
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link URL }
         *     
         */
        public URL getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link URL }
         *     
         */
        public void setValue(URL value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
