//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.14 at 03:40:33 PM EET 
//


package com.mobiblocks.skippables.vast;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for TrackingEvents_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackingEvents_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tracking" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *                 &lt;attribute name="event" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                       &lt;enumeration value="mute"/>
 *                       &lt;enumeration value="unmute"/>
 *                       &lt;enumeration value="pause"/>
 *                       &lt;enumeration value="resume"/>
 *                       &lt;enumeration value="rewind"/>
 *                       &lt;enumeration value="skip"/>
 *                       &lt;enumeration value="playerExpand"/>
 *                       &lt;enumeration value="playerCollapse"/>
 *                       &lt;enumeration value="start"/>
 *                       &lt;enumeration value="firstQuartile"/>
 *                       &lt;enumeration value="midpoint"/>
 *                       &lt;enumeration value="thirdQuartile"/>
 *                       &lt;enumeration value="complete"/>
 *                       &lt;enumeration value="acceptInvitationLinear"/>
 *                       &lt;enumeration value="timeSpentViewing"/>
 *                       &lt;enumeration value="progress"/>
 *                       &lt;enumeration value="creativeView"/>
 *                       &lt;enumeration value="acceptInvitation"/>
 *                       &lt;enumeration value="adExpand"/>
 *                       &lt;enumeration value="adCollapse"/>
 *                       &lt;enumeration value="minimize"/>
 *                       &lt;enumeration value="close"/>
 *                       &lt;enumeration value="overlayViewDuration"/>
 *                       &lt;enumeration value="otherAdInteraction"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="offset">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;pattern value="(\d{2}:[0-5]\d:[0-5]\d(\.\d\d\d)?|1?\d?\d(\.?\d)*%)"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class TrackingEventsType {

    @Nullable
    protected List<TrackingEventsType.Tracking> tracking;

    /**
     * Gets the value of the tracking property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tracking property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTracking().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrackingEventsType.Tracking }
     * 
     * 
     */
    @Nullable
    public List<TrackingEventsType.Tracking> getTracking() {
        return this.tracking;
    }
    
    public void addTracking(@NonNull TrackingEventsType.Tracking tracking) {
        if (this.tracking == null) {
            this.tracking = new ArrayList<>();
        }
        
        this.tracking.add(tracking);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
     *       &lt;attribute name="event" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *             &lt;enumeration value="mute"/>
     *             &lt;enumeration value="unmute"/>
     *             &lt;enumeration value="pause"/>
     *             &lt;enumeration value="resume"/>
     *             &lt;enumeration value="rewind"/>
     *             &lt;enumeration value="skip"/>
     *             &lt;enumeration value="playerExpand"/>
     *             &lt;enumeration value="playerCollapse"/>
     *             &lt;enumeration value="start"/>
     *             &lt;enumeration value="firstQuartile"/>
     *             &lt;enumeration value="midpoint"/>
     *             &lt;enumeration value="thirdQuartile"/>
     *             &lt;enumeration value="complete"/>
     *             &lt;enumeration value="acceptInvitationLinear"/>
     *             &lt;enumeration value="timeSpentViewing"/>
     *             &lt;enumeration value="progress"/>
     *             &lt;enumeration value="creativeView"/>
     *             &lt;enumeration value="acceptInvitation"/>
     *             &lt;enumeration value="adExpand"/>
     *             &lt;enumeration value="adCollapse"/>
     *             &lt;enumeration value="minimize"/>
     *             &lt;enumeration value="close"/>
     *             &lt;enumeration value="overlayViewDuration"/>
     *             &lt;enumeration value="otherAdInteraction"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="offset">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;pattern value="(\d{2}:[0-5]\d:[0-5]\d(\.\d\d\d)?|1?\d?\d(\.?\d)*%)"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Tracking {

        protected URL value;
        @NonNull
        protected String event;
        protected String offset;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link URL }
         *     
         */
        public URL getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link URL }
         *     
         */
        public void setValue(URL value) {
            this.value = value;
        }

        /**
         * Gets the value of the event property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEvent() {
            return event;
        }

        /**
         * Sets the value of the event property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEvent(String value) {
            this.event = value;
        }

        /**
         * Gets the value of the offset property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOffset() {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOffset(String value) {
            this.offset = value;
        }
    }

}
