//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.14 at 03:40:33 PM EET 
//


package com.mobiblocks.skippables.vast;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.math.BigInteger;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Ad" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="InLine" type="{http://www.iab.com/VAST}Inline_type" minOccurs="0"/>
 *                   &lt;element name="Wrapper" type="{http://www.iab.com/VAST}Wrapper_type" minOccurs="0"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="conditionalAd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class VAST {

    @Nullable
    protected ArrayList<VAST.Ad> ad;
    protected URL error;
    @NonNull
    protected String version;

    /**
     * Gets the value of the ad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VAST.Ad }
     * 
     * 
     */
    @Nullable
    public List<VAST.Ad> getAd() {
        return this.ad;
    }
    
    void addAd(VAST.Ad ad) {
        if (this.ad == null) {
            this.ad = new ArrayList<>();
        }
        
        this.ad.add(ad);
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link URL }
     *     
     */
    public URL getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link URL }
     *     
     */
    public void setError(URL value) {
        this.error = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public Ad getFirstAd() {
        if (this.ad == null || this.ad.size() == 0) {
            return null;
        }
        
        return this.ad.get(0);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="InLine" type="{http://www.iab.com/VAST}Inline_type" minOccurs="0"/>
     *         &lt;element name="Wrapper" type="{http://www.iab.com/VAST}Wrapper_type" minOccurs="0"/>
     *       &lt;/choice>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="conditionalAd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Ad {

        protected InlineType inLine;
        protected WrapperType wrapper;
        protected String id;
        protected int sequence;
        protected Boolean conditionalAd;

        /**
         * Gets the value of the inLine property.
         * 
         * @return
         *     possible object is
         *     {@link InlineType }
         *     
         */
        public InlineType getInLine() {
            return inLine;
        }

        /**
         * Sets the value of the inLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link InlineType }
         *     
         */
        public void setInLine(InlineType value) {
            this.inLine = value;
        }

        /**
         * Gets the value of the wrapper property.
         * 
         * @return
         *     possible object is
         *     {@link WrapperType }
         *     
         */
        public WrapperType getWrapper() {
            return wrapper;
        }

        /**
         * Sets the value of the wrapper property.
         * 
         * @param value
         *     allowed object is
         *     {@link WrapperType }
         *     
         */
        public void setWrapper(WrapperType value) {
            this.wrapper = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the sequence property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getSequence() {
            return sequence;
        }

        /**
         * Sets the value of the sequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSequence(int value) {
            this.sequence = value;
        }

        /**
         * Gets the value of the conditionalAd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isConditionalAd() {
            return conditionalAd;
        }

        /**
         * Sets the value of the conditionalAd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setConditionalAd(Boolean value) {
            this.conditionalAd = value;
        }

    }

}
