//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.14 at 03:40:33 PM EET 
//


package com.mobiblocks.skippables.vast;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 				Verification elements are nested under AdVerifications. The Verification element is used to contain the
 * JavaScript or Flash code used to collect data. Multiple Verification elements may be used in
 * cases where more than one verification vendor needs to collect data or when different API
 * frameworks are used.
 * 
 * When included, verification contents must be executed (if possible) BEFORE the
 * media file or interactive creative file is executed, to ensure verification can track ad
 * play as intended.
 * 			
 * 
 * <p>Java class for Verification_Inline_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Verification_Inline_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FlashResource" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *                 &lt;attribute name="apiFramework" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="JavaScriptResource" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *                 &lt;attribute name="apiFramework" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ViewableImpression" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="vendor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class VerificationInlineType {

    @Nullable protected List<VerificationInlineType.FlashResource> flashResource;
    @Nullable protected List<VerificationInlineType.JavaScriptResource> javaScriptResource;
    @Nullable protected VerificationInlineType.ViewableImpression viewableImpression;
    @Nullable protected String vendor;

    /**
     * Gets the value of the flashResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flashResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlashResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerificationInlineType.FlashResource }
     * 
     * 
     */
    @Nullable
    public List<VerificationInlineType.FlashResource> getFlashResource() {
        return this.flashResource;
    }
    
    public void addFlashResource(@NonNull VerificationInlineType.FlashResource flashResource) {
        if (this.flashResource == null) {
            this.flashResource = new ArrayList<>();
        }
        this.flashResource.add(flashResource);
    }

    /**
     * Gets the value of the javaScriptResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the javaScriptResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJavaScriptResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerificationInlineType.JavaScriptResource }
     * 
     * 
     */
    @Nullable
    public List<VerificationInlineType.JavaScriptResource> getJavaScriptResource() {
        return this.javaScriptResource;
    }

    public void addJavaScriptResource(@NonNull VerificationInlineType.JavaScriptResource javaScriptResource) {
        if (this.javaScriptResource == null) {
            this.javaScriptResource = new ArrayList<>();
        }
        this.javaScriptResource.add(javaScriptResource);
    }

    /**
     * Gets the value of the viewableImpression property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationInlineType.ViewableImpression }
     *     
     */
    public VerificationInlineType.ViewableImpression getViewableImpression() {
        return viewableImpression;
    }

    /**
     * Sets the value of the viewableImpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationInlineType.ViewableImpression }
     *     
     */
    public void setViewableImpression(VerificationInlineType.ViewableImpression value) {
        this.viewableImpression = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
     *       &lt;attribute name="apiFramework" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class FlashResource {

        protected URL value;
        protected String apiFramework;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link URL }
         *     
         */
        public URL getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link URL }
         *     
         */
        public void setValue(URL value) {
            this.value = value;
        }

        /**
         * Gets the value of the apiFramework property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApiFramework() {
            return apiFramework;
        }

        /**
         * Sets the value of the apiFramework property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApiFramework(String value) {
            this.apiFramework = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
     *       &lt;attribute name="apiFramework" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class JavaScriptResource {

        protected URL value;
        protected String apiFramework;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link URL }
         *     
         */
        public URL getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link URL }
         *     
         */
        public void setValue(URL value) {
            this.value = value;
        }

        /**
         * Gets the value of the apiFramework property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApiFramework() {
            return apiFramework;
        }

        /**
         * Sets the value of the apiFramework property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApiFramework(String value) {
            this.apiFramework = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class ViewableImpression {

        protected URL value;
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link URL }
         *     
         */
        public URL getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link URL }
         *     
         */
        public void setValue(URL value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
