# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Skippables_Sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Skippables_Sample


pod 'Skippables', :path => '/Users/daniel/Dev/iOS/skipp/pub/Skippables.podspec'


end
